### ISSUE TITLE
Add tour categories

### ISSUE THREAD

**Issue by Saela** [gipfeli-io/gipfeli-frontend#123]
- Add possibility to set categories for a tour. 
- Display category in detail view

# Review

- [x] Code is written
- [ ] Tests (if necessary) are written
- [ ] Code is documented (either in documentation itself or in code)
- [x] Code is reviewed
- [x] Must implement functionality specified in the ticket and in line with the design specifications (e.g. wireframes)
- [x] Build is successful (including all tests passed)
- [x] Deployment to staging works
- [x] Manual testing on staging by peer

**Comment by Tugark** [comment]
Maybe also add countries, and date? :D
