### ISSUE TITLE
Add Signup functionality (form) in frontend

### ISSUE THREAD

**Issue by Saela** [gipfeli-io/gipfeli-frontend#25]
- Add sign up form
- Integrate api endpoint for sign up
- Add error handling
- Add success information
- 
# Review

- [x] Code is written
- [x] Tests (if necessary) are written
- [x] Code is documented (either in documentation itself or in code)
- [ ] Code is reviewed
- [x] Must implement functionality specified in the ticket and in line with the design specifications (e.g. wireframes)
- [x] Build is successful (including all tests passed)
- [x] Deployment to staging works
- [ ] Manual testing on staging by peer

**Comment by Tugark** [comment]
See #51 , this is still open.

**Comment by Tugark** [comment]
Closing this, the #51 will be tackled in another sprint.
