### ISSUE TITLE
Add form to upload image

### ISSUE THREAD

**Issue by Saela** [gipfeli-io/gipfeli-frontend#46]
Add simple form to upload image (without gps data)

Workflow:
1. When user uploads image we send it to api
2. Api will upload image to cloud storage and return handle
3. Then we will try to extract the gps data (will be done in another sprint)
4. Api adds handle and gps data to image table (without link to tour)
5. Api will return handle and gps data to frontend
6. Frontend will display image directly in app (will be done in another sprint)
7. When the user saves the tour the images will be linked to it
8. Cronjob will remove unlinked images

# Review

- [ ] Code is written
- [ ] Tests (if necessary) are written
- [ ] Code is documented (either in documentation itself or in code)
- [ ] Code is reviewed
- [ ] Must implement functionality specified in the ticket and in line with the design specifications (e.g. wireframes)
- [ ] Build is successful (including all tests passed)
- [ ] Deployment to staging works
- [ ] Manual testing on staging by peer

**Comment by Tugark** [comment]
See also ticket https://github.com/gipfeli-io/gipfeli-api/issues/54 - we can document these things there.

**Comment by Tugark** [comment]
See also ticket https://github.com/gipfeli-io/gipfeli-api/issues/54 - we can document these things there.
