### ISSUE TITLE
[BUG]: Offline functionality

### ISSUE THREAD

**Issue by Tugark** [gipfeli-io/gipfeli-frontend#78]
### Description of the bug

I noticed some things.

### Steps To Reproduce

Desktop browser, "fake offline":
* Sometimes, an edit does not get the EDIT symbol, even though it is edited
* Editing an entry > go to tour list > edit entry has symbol > create a new tour > edited entry no longer has the symbol
* We might have a caching issue - if you visited a detail page that has images, then go back to tour edit, then turn on offline -> when you access the tour detail page again, it throws because it tries to access `tour.images.length` where images is undefined. It only works if you are on the detail page when you go offline. => **fixed by catching if tour.images are undefined or not.**

Phone:
* Clearing the index db is... near impossible? :D => **done by introducing reset functionality**

**Comment by Saela** [comment]
could not reproduce the missing edit symbol.
